//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contensive.Addons.aoPortal.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Contensive.Addons.aoPortal.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //
        ///// adminFramework assembly referenced js
        /////
        ///if (typeof google !== &apos;object&apos;) {
        ///    document.write(&apos;&lt;scr&apos; + &apos;ipt type=&quot;text/javascript&quot; src=&quot;https://www.google.com/jsapi&quot;&gt;&lt;/scr&apos; + &apos;ipt&gt;&apos;);
        ///}
        ///function cjFrameSubmitForm(remoteMethodName, frameHtmlId, formHtmlId) {
        ///    jQuery(&apos;#&apos; + frameHtmlId).block();
        ///    cj.ajax.addon(
        ///        remoteMethodName
        ///        , &apos;frameName=&apos; + frameHtmlId
        ///        , formHtmlId
        ///        , frameHtmlId
        ///    );
        ///}
        ///function cjFrameUpdate(remoteMethodName, frameHtmlId, qs) {
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string javascript {
            get {
                return ResourceManager.GetString("javascript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ////*
        ///* AdminFramework assembly referenced resources
        ///*/
        ///#desktop 
        ///{
        ///    background-color: #999;
        ///}
        ///#afw #afwBodyFrame 
        ///{
        ///    background-color: white;
        ///}
        ///#afw,#afw p,#afw div,#afw td,#afw li
        ///{
        ///    font-family: arial;   
        ///    font-size: 13px;    
        ///    font-weight: normal;
        ///    line-height: 20px;
        ///}
        ///#afw h1,#afw h2,#afw h3,#afw h3
        ///{
        ///    font-family: arial;   
        ///    font-weight: bold;
        ///}
        ///#afw h1
        ///{
        ///    font:normal bold 20px/30px Arial, san-serif;
        ///    margin: 20px 0 10px 0;
        ///}
        ///#afw h2
        ///{
        ///    fon [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string styles {
            get {
                return ResourceManager.GetString("styles", resourceCulture);
            }
        }
    }
}
